In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([  4,  70,  85, -78,  21,  72])

In [6]:
tensor = torch.tensor([[0.1,0.2],[0.3,0.4],[0.5,0.6]])
tensor

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000],
        [0.5000, 0.6000]])

In [8]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
input1 = torch.empty(2,3)
input1

tensor([[1.1273e-08, 4.4291e-41, 1.7450e+30],
        [3.2004e-41, 4.4842e-44, 0.0000e+00]])

In [11]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [13]:
linspace= torch.linspace(3,10,steps=6)
linspace

tensor([ 3.0000,  4.4000,  5.8000,  7.2000,  8.6000, 10.0000])

In [14]:
logspace = torch.logspace(start=-10,end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [17]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [35]:
a = torch.empty((2,3), dtype=torch.int64)
a

tensor([[ 98094666146288,  98094666320880,              80],
        [             64,  98075087991555, 135751519067360]])

In [36]:
empty1 = torch.empty_like(a)
empty1

tensor([[ 98094665383104,  98094665439760,              24],
        [135751864943568, 135746622863728,              25]])

In [39]:
import torch

x = torch.ones(2, 3)  # Creates a 2x3 tensor filled with ones
y = torch.empty_like(x)  # Creates another 2x3 tensor with uninitialized values
print(y)

tensor([[-3.7765e+34,  4.4288e-41,  1.1351e-43],
        [ 0.0000e+00,  1.1273e-08,  4.4291e-41]])


In [41]:
import torch
import time
import numpy as np 
device  = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [46]:
start_time = time.time()
zero = torch.zeros(1,1)
end_time = time.time()
print(f' total time : {end_time - start_time : 10f}')

 total time :   0.000233


In [57]:
%%time
torch_rand_tensor_1 = torch.rand(100,100,100,100).to(device)
torch_rand_tensor_2 = torch.rand(100,100,100,100).to(device)

np_rand_1 = torch.rand(100,100,100,100)
np_rand_2 = torch.rand(100,100,100,100)

start_time = time.time()

rand_tensor = (torch_rand_tensor_1 @ torch_rand_tensor_2)

end_time = time.time()

print(f' total time : {end_time - start_time : 10f}')

start_time = time.time()

rand_np = np.multiply(np_rand_1,np_rand_2)

end_time = time.time()
print(f' total time : {end_time - start_time : 10f}')

 total time :   0.000559
 total time :   0.083157
CPU times: user 1.45 s, sys: 370 ms, total: 1.82 s
Wall time: 1.81 s


In [51]:
torch_rand_tensor_1.size()

torch.Size([100, 100, 100, 100])

In [56]:
torch_rand_tensor_1[0][0][0]

tensor([0.8887, 0.5923, 0.6005, 0.0260, 0.1581, 0.1934, 0.8898, 0.3742, 0.6202,
        0.4810, 0.6941, 0.1559, 0.8572, 0.5317, 0.2281, 0.5980, 0.8265, 0.2034,
        0.5838, 0.1994, 0.9865, 0.0103, 0.5401, 0.7153, 0.8773, 0.2133, 0.9266,
        0.3443, 0.7334, 0.6442, 0.3077, 0.6929, 0.8553, 0.1287, 0.4603, 0.2150,
        0.8735, 0.1418, 0.6749, 0.0951, 0.2546, 0.5867, 0.2652, 0.8241, 0.0794,
        0.5018, 0.8295, 0.6131, 0.4356, 0.5829, 0.1755, 0.0338, 0.8113, 0.1069,
        0.0357, 0.0369, 0.8634, 0.6515, 0.2627, 0.0389, 0.2428, 0.2450, 0.0281,
        0.9208, 0.3115, 0.7315, 0.8487, 0.5799, 0.6158, 0.8574, 0.2041, 0.3736,
        0.1848, 0.4465, 0.5589, 0.7433, 0.3898, 0.6742, 0.3056, 0.2691, 0.4745,
        0.6456, 0.5237, 0.6981, 0.6058, 0.9609, 0.1604, 0.6961, 0.5877, 0.5841,
        0.0358, 0.6552, 0.7978, 0.0229, 0.9951, 0.8314, 0.9052, 0.4995, 0.6920,
        0.4744], device='cuda:0')

In [ ]:
probailities = torch.tensor([0.1,0.9])
